// Generated by Wrangler on Sun Jun 23 2024 14:41:06 GMT+0300 (Moscow Standard Time)
// by running `wrangler types`

interface Env {
	ZIPLINE_URL_BASE: "https://i.0hz.me";
	CF_API_KEY: string;
	TG_BOT_TOKEN: string;
	ZONE_ID: string;
	TG_NOTIFY_CONTACT_ID: string;
}
